name: sanity checks on opened pull requests

on:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - 'aim/sdk/**'
      - 'aim/web/api/**'
      - 'aim/storage/**'
      - '.github/workflows/pull-request.yml'
      - 'tests/**'
      - 'performance_tests/**'
      - 'setup.py'
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
jobs:
  run-checks:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Run Unit-tests & Code-style checks
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.dev.txt
      - name: code style checks
        run: |
          flake8 aim
      - name: unit-tests
        run: |
          pytest --cov-report term --cov-branch --cov-fail-under=50 --cov=aim/web --cov=aim/storage --cov=aim/sdk tests
  storage-performance-checks:
    needs: run-checks
    concurrency: perf-tests
    runs-on: self-hosted
    name: Performance tests
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: install deps
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.dev.txt
      - name: perf tests
        run: |
         . venv/bin/activate
         export AWS_ACCESS_KEY_ID=${{ secrets.AIM_LOGS_AWS_ACCESS_KEY_ID }}
         export AWS_SECRET_ACCESS_KEY=${{ secrets.AIM_LOGS_AWS_SECRET_ACCESS_KEY }}
         pytest performance_tests || pytest --lf performance_tests
